# the name for the generated package.
# default: slogattr
pkg: slogattr

# the list of packages to import.
# should only be filled in if non-basic types are used.
# default: []
imports:
  - time

# the attributes to generate constructors for.
# format: <key:type>
# default: {}
attrs:
  user_id: int
  created_at: time.Time
  err: error
