name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  test:
    uses: go-simpler/.github/.github/workflows/test.yml@main
    with:
      go-versions: '[ "stable" ]' # current "oldstable" (1.20) can't parse the new go.mod format.
  lint:
    uses: go-simpler/.github/.github/workflows/lint.yml@main
  vuln:
    uses: go-simpler/.github/.github/workflows/vuln.yml@main
  generate:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate code
        run: go generate ./... && git diff --exit-code
